#!/usr/bin/env bash

# This small script is under the GPLv3 license.

# It is intender to use in debian systems
# other distros are not supported.

set -o errexit   # exit on error

# colors
function minifetch_set_colors ()
{
    title_color="\e[1;34m" # titles
    ascii_color="\e[1;31m" # ascii logo
    info_color="\e[0;32m"  # info
    reset_colors="\e[0m"   # reset_colors coloring
}

function minifetch_get_system_info ()
{
    debian_version="debian $(cat /etc/debian_version)"
    sysarch="$HOSTTYPE"
    desktop=$(echo $XDG_CURRENT_DESKTOP | awk '{print tolower($0)}')
    shell="$(basename $SHELL)"
    packages="$(dpkg -l | grep -c ^i)"
    kernel="$(uname -rs | awk '{print tolower($0)}')"
    uptime="$(uptime -p | sed "s/up //")"
}

function minifetch_print_information ()
{
    printf "+---------------+\n"
    printf "|${ascii_color}    .ooooo+.   ${reset_colors}|  ${title_color}os:       ${info_color}${debian_version}${reset_colors}\n"
    printf "|${ascii_color}  .oo+....o=+  ${reset_colors}|  ${title_color}kernel:   ${info_color}${kernel}${reset_colors}\n"
    printf "|${ascii_color}  o+  ...  oo  ${reset_colors}|  ${title_color}desktop:  ${info_color}${desktop}${reset_colors}\n"
    printf "|${ascii_color}  =   +.  .+.  ${reset_colors}|  ${title_color}shell:    ${info_color}${shell}${reset_colors}\n"
    printf "|${ascii_color}  oo   ....    ${reset_colors}|  ${title_color}packages: ${info_color}${packages}${reset_colors}\n"
    printf "|${ascii_color}   ++.         ${reset_colors}|  ${title_color}sysarch:  ${info_color}${sysarch}${reset_colors}\n"
    printf "|${ascii_color}    .+.        ${reset_colors}|  ${title_color}uptime:   ${info_color}${uptime}${reset_colors}\n"
    printf "+---------------+\n"
}

# run the stuff
minifetch_set_colors
minifetch_get_system_info
minifetch_print_information
